arch: x86_64
image: archlinux
packages:
  - docker
  - docker-buildx
secrets:
  -  96d6709d-1469-48b7-8ec2-0e5113821f31
environment:
  DOCKER_USER: 'SCWSKTWJR9ZP1H501BTA'
sources:
  - https://git.sr.ht/~jae/Overengine
tasks:
  - build: |
      sudo mount -t tmpfs -o size=4G /dev/null /dev/shm
      sudo systemctl start docker
      sleep 2
      sudo nohup dockerd --bip 172.18.0.1/16 </dev/null >/dev/null 2>&1 &
      sudo usermod -aG docker $(whoami)
      sleep 10
      cd Overengine
      sudo cat ~/docker-key | sudo docker login -u "$DOCKER_USER" --password-stdin=true rg.nl-ams.scw.cloud
      sudo docker buildx create --use
      sudo docker buildx build --push --platform=linux/amd64 -t rg.nl-ams.scw.cloud/jaexencont/overengine:latest . 
