arch: x86_64
image: archlinux
packages:
  - docker
secrets:
  -  e4b4e45e-b74b-443d-838f-eba61a0d2e0d
environment:
  DOCKER_USER: 'jae'
sources:
  - https://git.sr.ht/~jae/Overengine
tasks:
  - build: |
      sudo mount -t tmpfs -o size=4G /dev/null /dev/shm
      sudo systemctl start docker
      sleep 2
      sudo nohup dockerd --bip 172.18.0.1/16 </dev/null >/dev/null 2>&1 &
      sudo usermod -aG docker $(whoami)
      sleep 10
      cd Overengine
      docker build -t rg.nl-ams.scw.cloud/jaexencont/overengine:latest . ; docker push rg.nl-ams.scw.cloud/jaexencont/overengine:latest
