arch: x86_64
image: archlinux
packages:
  - docker
  - docker-buildx
secrets:
  -  88343b8e-5e4e-4088-ba2e-5efc27d8f584
environment:
  DOCKER_USER: 'jae'
sources:
  - https://git.sr.ht/~jae/Overengine
tasks:
  - build: |
      sudo mount -t tmpfs -o size=4G /dev/null /dev/shm
      sudo systemctl start docker
      sleep 2
      sudo nohup dockerd --bip 172.18.0.1/16 </dev/null >/dev/null 2>&1 &
      sudo usermod -aG docker $(whoami)
      sleep 10
      cat ~/docker_reg_pass | sudo docker login -u "$DOCKER_USER" --password-stdin=true reg.jae.fi
      cd Overengine
      sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      sudo docker buildx create --use
      sudo docker buildx build --push --platform=linux/amd64,linux/arm64 -t reg.jae.fi/jae/overengine:latest . 
