stages:
  - test
  - build

test-lint:
  stage: test
  image: node:current-alpine
  cache:
    - paths:
        - node_modules/
        - .yarn
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
  script:
    - yarn lint
    - yarn prettier
  needs: []

test-tests:
  stage: test
  image: node:current-alpine
  cache:
    - paths:
        - node_modules/
        - .yarn
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
  script:
    - yarn test:ci
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  needs: []

build-push:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME%+*}
  only:
    - branches
    - tags
  needs: ["test-lint", "test-tests"]

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
